Import "Customize Image" doc to beta docs
astronomer/cloud-docs pull request #82
Opened 2021-09-08 21:39 UTC by jwitz

Resolves https://github.com/astronomer/beta-docs/issues/69

Cleaned up a lot of the language from the existing doc, so treat this as if you were reviewing a new doc

Not in the sidebar yet - will add it once we merge the other PR with the other 2 Runtime docs.

2021-10-05 18:35 UTC, paolaperaza requested changes
Some comments here - back to you @jwitz

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +When you first initialize a new Airflow project on Astronomer, a file called `airflow_settings.yaml` is automatically generated. With this file, you can configure and programmatically generate Airflo
```suggestion
When you first initialize a new Astronomer project, a file called `airflow_settings.yaml` is automatically generated. With this file, you can configure and programmatically generate Airflow Connections, Pools, and Variables when you're developing locally.
```

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +For security reasons, the `airflow_settings.yaml` file is currently only for local development and should not be used for pushing up code to Astronomer via `astro deploy`. For the same reason, we rec
Maybe format this as a "tip"

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +## Configure `airflow_settings.yaml` (Local Development Only)
Let's add more information to this section so that we're not just telling people "hey this file exists and you can use it"! See if you can test this out yourself and rework this section a bit with few steps that look something like this:

1. Open your `airflow_settings.yaml` file
2. In the yaml template, add any Airflow Connections, Pools, or Variables (link out to Airflow OSS docs )
3. Rebuild your image by running astro dev stop > astro dev start
4. Check the Airflow UI (localhost:8080) to see that your Airflow Connections/Variables/Pools now render

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +By default, the `airflow_settings.yaml` file is be structured as following:
```suggestion
By default, the `airflow_settings.yaml` file includes the following template:
```

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +FROM quay.io/astronomer/astro-runtime:3.0.1-buster-onbuild
```suggestion
FROM quay.io/astronomer/astro-runtime:3.0.3
```

@jwitz Can we use Env Var here to keep this reference to Runtime "latest"?

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +The Astronomer CLI is built on top of [Docker Compose](https://docs.docker.com/compose/), a tool for defining and running multi-container Docker applications. To override any of the Astronomer CLI's
This links out to our old CLI repo. @kushalmalani In Gen2 CLI, do you know if users can still add a docker-compose override file the same way they could with Gen1? What's the equivalent of this:

https://github.com/astronomer/astro-cli/blob/main/airflow/include/composeyml.go

In Gen2 CLI?

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +Refer to the [Airflow CLI documentation](https://airflow.apache.org/docs/apache-airflow/stable/usage-cli.html) for a list of all commands.
My understanding was that people could run Airflow CLI commands with `astro dev run` - can you verify + test? Let's get rid of docker commands if we can

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +    > **Note:** Do not include `-onbuild` at the end of your Airflow Image as you typically would in your `Dockerfile`.
Let's be clearer here -

>     If you're running the Astronomer Runtime image 3.0.3, for example, this would be:
> 
>     ```
>     FROM quay.io/astronomer/astro-runtime:3.0.3-base AS stage
>     ```

The onbuild thing is gen 1 only. Here we have to explain the difference between `3.0.3-base` and `3.0.3` or link out here: https://docs.astronomer.io/runtime-versioning#runtime-images

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +    COPY --from=stage2 /usr/lib/python3.6/site-packages/ /usr/lib/python3.6/site-packages/
```suggestion
    COPY --from=stage2 /usr/lib/python3.9/site-packages/ /usr/lib/python3.9/site-packages/
```

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +    COPY --from=stage2 /usr/lib/python3.6/site-packages/ /usr/lib/python3.6/site-packages/
Runtime is Python 3.9: https://docs.astronomer.io/runtime-release-notes#astronomer-runtime-301

Per Andrew's comment, we don't want people customizing this

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +If you have `quay.io/astronomer/astro-runtime:3.0.1-buster` in your `Dockerfile.build`, for example, this command would be:
```suggestion
If you have `quay.io/astronomer/astro-runtime:3.0.3-base` in your `Dockerfile.build`, for example, this command would be:
```

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +docker build -f Dockerfile.build --build-arg PRIVATE_RSA_KEY="$(cat ~/.ssh/id_rsa)" -t custom-astro-runtime:3.0.1-buster .
```suggestion
docker build -f Dockerfile.build --build-arg PRIVATE_RSA_KEY="$(cat ~/.ssh/id_rsa)" -t custom-astro-runtime:3.0.3-base .
```

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +If you're based your custom image off of `quay.io/astronomer/astro-runtime:3.0.1-buster`, for example, this line would read:
```suggestion
If you're based your custom image off of `quay.io/astronomer/astro-runtime:3.0.3-base`, for example, this line would read:
```

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +FROM custom-astro-runtime:3.0.1-buster
```suggestion
FROM custom-astro-runtime:3.0.3-base
```

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +    - If you're running Python 3.7 on your machine, replace the reference to Python 3.6 under `# Copy requirements directory` with `/usr/lib/python3.7/site-packages/` above
```suggestion
```

Remove this - we won't support other versions of Python

2021-10-05 18:35 UTC, paolaperaza commented on docs/customize-image.md
> +The Astronomer Runtime Docker image has been tested and built only for Python 3.7.
Yea, let's remove this Jake

2021-10-05 18:49 UTC, kushalmalani commented on docs/customize-image.md
> +The Astronomer CLI is built on top of [Docker Compose](https://docs.docker.com/compose/), a tool for defining and running multi-container Docker applications. To override any of the Astronomer CLI's
https://github.com/astronomer/astrohub-cli/blob/main/airflow/include/composeyml.go

2021-10-06 12:07 UTC, jwitz reviewed
Some changes and some questions here @paolaperaza , I think we need to scope:

- The context of image customization generally (is it something you only do when you start a project?)
- The context of local-only customizations (should we move those to Develop Locally?)

2021-10-06 12:07 UTC, jwitz commented on docs/customize-image.md
> +The Astronomer CLI is built on top of [Docker Compose](https://docs.docker.com/compose/), a tool for defining and running multi-container Docker applications. To override any of the Astronomer CLI's
This repository is private. Does it make sense to remove this section if they don't know what configurations are possible to override?

2021-10-12 00:25 UTC, paolaperaza reviewed
@jwitz Don't kill me, but as I'm reviewing the rest of this PR and thinking more about this, I think I'm gonna propose the following doc file scaffolding instead:

1. Rename `Develop Locally` as-is to `Create an Astronomer Project`. This doc is required and should be in the `Getting Started` folder. It would include:
     - Create an Astronomer Project
     - Make Changes to your Project
 
From this doc in its current state, basically just remove "Access Airflow Logs" and "Run Airflow CLI commands".

2. Create a `Customize your Astronomer Project` doc that's 1:1 with `Customizing your Image`. This is more of a "reference" doc that people can use once they're ready to add their own stuff.
   - Add Python Packages
   - Add dependencies
   - Run Airflow CLI commands
   - etc etc

3. Create a NEW `Troubleshoot Locally` doc that covers:
     - Accessing Airflow task logs in the Airflow UI
     - Accessing Airflow Component Logs via `astro dev logs`
     - Maybe testing Airflow Connections (new feature in Airflow 2.2)
     - Talk to other teams to see what else would be helpful here

I know it's a slight pivot from this PR and our conversation this morning, but I think this separates out the sort of foundational "what is my project and what do I make changes" information from the "ok what are all the things I could add here to fulfill my use case" and then "how can I use Astronomer to test this stuff locally and make sure it works". WDYT?

2021-10-12 00:25 UTC, paolaperaza commented on docs/create-project.md
> +To create a new Astronomer project folder, open an empty directory and run `astro dev init`. This command generates the following files in the directory:
Could maybe add a tip here too:

> Tip: To confirm that you installed the Astronomer CLI in your directory, run `ls`. You should see a file called `astro`.

2021-10-12 11:14 UTC, jwitz commented on docs/create-project.md
> +These files make up the Docker image that runs in your local Airflow environment.
What about: `These files are necessary for building a Docker image that can run Airflow pipelines on either your local machine or Astronomer Cloud.`

2021-10-12 11:17 UTC, jwitz commented on docs/create-project.md
> +To test your local Astronomer project, run `astro dev start` from your project directory. This command builds your project and spins up 3 Docker containers on your machine to run it.
This information is included in the current Develop Locally doc, under the step to run the project locally. Because this is more of a "confirmation" step, I didn't think this more reference-y material belonged here.

2021-10-12 11:45 UTC, jwitz commented
@paolaperaza Made some changes and comments based on your inline review. As for the high level structure suggestion, I have a few reservations before jumping into this:

- I don't think "Create a Project" should be in our Getting Started collection. Currently that folder contains one-time installation tasks, and I imagine that people will need to reference this doc more than once when creating multiple projects. Including a "making changes" section in a "Getting Started" doc also feels odd in scope.
- Feels like we're taking a step backwards by sticking with "Customizing" language in our local development docs. Features like using `airflow-settings.yaml` don't really fit the definition of customization, as you're creating Airflow objects to use in the project vs. defining the project itself. If anything, that should be in the potential "Troubleshoot" doc because it lets you quickly create new Airflow resources on the fly locally. Most of the details in the current _draft_ of the doc are related to development, and I think that should remain the focus here. 
- Will the troubleshooting doc have OSS troubleshooting info as well, such as for rerunning DAGs, checking DAG status, etc? Though this change is minor in terms of content, it would represent a significant change in our documentation scope - I'd prefer to tackle that doc in a separate PR to avoid scope creep, as well as to get some of this info out here for people to use/ comment on.
- In this current structure, there is no place to discuss running Airflow locally. Assume that's what you mean by "Make Changes to your Project", but that's slightly different in scope. Someone might want to learn how to run locally without necessarily making a change to their project.

I do like the idea of moving away from "local" as a concept related to projects and using it exclusively in relation to `astro dev start` etc. So with that in mind, here's a counterproposal of sorts building on yours:

- Have a Create a Project file as we currently do, but do not include steps for rebuilding a project and do not include this in Getting Started.
- Have a Develop Your Astronomer Project doc, which covers any action that relates to making a change to a file and seeing that change in _any_ environment, local or Cloud.
- Test/ Troubleshoot doc that covers any action that relates to running locally, running commands - basically anything that _doesn't_ require a code change. This is now the primary file where we discuss `astro dev start` and related commands. Scope in relation to OSS Airflow troubleshooting features tbd.

The location of our "Run Airflow Locally" info is definitely up for debate, but I feel pretty confident with the rest of these suggestions.

2021-10-29 18:16 UTC, jwitz commented on docs/develop-project.md
> +All Astronomer projects require you to specify a Debian-based Astronomer Runtime image in a `Dockerfile`. When you run your project locally or on Astronomer Cloud, all of your DAG code, packages, and
"based on Astronomer Runtime?"

2021-10-29 18:17 UTC, jwitz commented on docs/develop-project.md
> +To restart a locally running Astronomer project, run the following two commands:
I like "Restart Your Local Environment"! Don't think it's wordy.

2021-10-29 18:22 UTC, jwitz commented on docs/develop-project.md
> +As a security measure, `airflow_settings.yaml` works only in local environments. If you deploy your project to a Deployment, the values in this file will not be pushed. To more easily manage your Air
I can switch to "values", they're pretty much the same

2021-10-29 18:31 UTC, jwitz commented
Back to you @paolaperaza ! We've changed a few headers and file names in here, so once you do another pass I'll go back in and make sure all of our hyperlinks are sound (gotta run for now tho)

2021-11-02 01:15 UTC, paolaperaza commented on docs/develop-project.md
> +- Add environment variables locally
Remove "Run Airflow CLI commands" here. Also, should this bullet list actually match the H2s in this doc maybe?

2021-11-02 01:15 UTC, paolaperaza commented on docs/develop-project.md
> +To develop locally, you need:
```suggestion
To customize an Astronomer project and test it locally, you need:
```

2021-11-02 01:15 UTC, paolaperaza commented on docs/develop-project.md
> +## Build and Run a Project
```suggestion
## Build and Run a Project Locally
```

2021-11-02 01:15 UTC, paolaperaza commented on docs/develop-project.md
> +The Astronomer CLI is a wrapper around [Docker Compose](https://docs.docker.com/compose/), a tool for defining and running multi-container Docker applications. If you're familiar with Docker Compose,
```suggestion
The Astronomer CLI is a wrapper around [Docker Compose](https://docs.docker.com/compose/), a tool for defining and running multi-container Docker applications. If you're familiar with Docker Compose, you'll recognize that the `astro dev start` command, for example, is functionally equivalent to `docker compose start`.
```

2021-11-02 01:15 UTC, paolaperaza commented on docs/develop-project.md
> +All changes made to the following files will be live in your project as soon as you save them to your code editor:
```suggestion
All changes made to the following files will be live in your local Airflow environment as soon as you save them to your code editor:
```

2021-11-02 01:15 UTC, paolaperaza commented on docs/develop-project.md
> +> **Note:** Note: As you develop locally, it may be necessary to reset your Docker containers and metadata DB for testing purposes. To do so, run `astro dev kill` instead of `astro dev stop` when reb
I suppose we could consolidate this info up there? The `astro dev kill` stuff and maybe just link out to section above instead of re-stating astro dev start > astro dev stop.

Don't feel strongly about this one tho - up to you

2021-11-02 01:15 UTC, paolaperaza commented on docs/develop-project.md
> +Once you've saved those packages in your project files, [restart your local environment](develop-project#restart-your-local-environment). When you access the Airflow UI for your project at `localhost
```suggestion
Once you've saved these values in your `airflow_settings.yaml`, [restart your local environment](develop-project#restart-your-local-environment). When you access the Airflow UI for your project at `localhost:8080`, you should see these values in the **Connections**, **Pools**, and **Variables** tabs.
```

2021-11-02 01:15 UTC, paolaperaza commented on docs/develop-project.md
> +<pre><code parentName="pre">{`FROM quay.io/astronomer/astro-runtime:${siteVariables.runtimeVersion}
Is this missing the actual `RUN ls`? This can be a next step but I also wonder if maybe we can ask the team what a common RUN command is and add it here

2021-11-02 01:15 UTC, paolaperaza commented on docs/develop-project.md
> +## Add Environment Variables (Local development only)
```suggestion
## Add Environment Variables (Local Development only)
```

I don't care either way but making this consistent with the above

2021-11-02 01:15 UTC, paolaperaza commented on docs/install-cli.md
> +Now that you've installed the Astronomer CLI, you're ready to create a local Airflow environment and start developing locally. For instructions, read [Create an Astronomer Project](create-project).
```suggestion
Now that you've installed the Astronomer CLI, you're ready to create an Astronomer project and start developing locally. For instructions, read [Create an Astronomer Project](create-project).
```

2021-11-02 01:15 UTC, paolaperaza commented on docs/test-and-troubleshoot-locally.md
> +Whenever you want to test your code, the first step is always to start a local Airflow environment. To run an Airflow locally, run:
```suggestion
Whenever you want to test your code, the first step is always to start a local Airflow environment. To build your Astronomer project locally, run:
```

2021-11-02 01:15 UTC, paolaperaza commented on docs/test-and-troubleshoot-locally.md
> +```
Thoughts on just cutting this out and keeping the last sentence here that links out to develop project?

2021-11-02 01:15 UTC, paolaperaza commented on docs/test-and-troubleshoot-locally.md
> +1. Access the Airflow UI in your local Airflow environment.
```suggestion
1. Access the Airflow UI in your local Airflow environment by going to http://localhost:8080.
```

2021-11-02 01:19 UTC, paolaperaza commented on docs/develop-project.md
> +All Astronomer projects require you to specify a Debian-based Astronomer Runtime image in a `Dockerfile`. When you run your project locally or on Astronomer Cloud, all of your DAG code, packages, and
Ya I think you got it here

2021-11-02 01:24 UTC, paolaperaza commented on docs/develop-project.md
> +Once you've saved those packages in your project files, [restart your local environment](develop-project#restart-your-local-environment). When you access the Airflow UI for your project at `localhost
i don't think we're doing anything w packages here in this airflow_settings.yaml section

2021-11-02 01:27 UTC, paolaperaza approved these changes
@jwitz I think I am finally an APPROVE here! A few final minor comments but this structurally looks great. Thanks for very gracefully working together on this review. This is a bug one!

I'll defer on the rest of my comments here and let you merge whenever you're ready. Do make sure to give all links a TRIPLE check since we're moving stuff around a good bit. 🚀

2021-11-02 14:46 UTC, jwitz commented
Let's go 🚀  thankfully our build check now fully fails if there's even a single broken link, so this is good to go! Only other change I made was to update the Test and Troubleshoot sidebar label

2021-11-02 14:47 UTC, merged